[Settings]
ID = "78c114cf-1bff-4d30-8899-92eacaec9f9a"

[build.environment]
  # NODE_VERSION = "18.6.0"
  NODE_VERSION = "17.9.0"
  NPM_VERSION = "8.14.0"
  # NPM_VERSION = "8.13.2"
  YARN_VERSION = "1.22.19"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

    Content-Security-Policy = "default-src 'self' cdnjs.cloudflare.com connect.facebook.net www.google-analytics.com www.googletagmanager.com; script-src 'report-sample' 'self' 'unsafe-eval' 'unsafe-inline' vidstat.taboola.com js-eu1.hscollectedforms.net js-eu1.hs-banner.com js-eu1.hs-analytics.net js-eu1.hs-scripts.com sb.scorecardresearch.com gum.criteo.com cdn.taboola.com cdn.ampproject.org snap.licdn.com adservice.google.com adservice.google.nl c.disquscdn.com connect.facebook.net d33wubrfki0l68.cloudfront.net menefex.disqus.com links.services.disqus.com maps.googleapis.com pagead2.googlesyndication.com partner.googleadservices.com tpc.googlesyndication.com unpkg.com www.google-analytics.com www.google.com www.googletagmanager.com www.googletagservices.com www.gstatic.com; style-src 'report-sample' 'self' 'unsafe-inline' cdnjs.cloudflare.com fonts.googleapis.com c.disquscdn.com; object-src 'none'; base-uri 'self'; connect-src 'self' region1.analytics.google.com	js-eu1.hs-banner.com forms-eu1.hubspot.com region1.google-analytics.com web.facebook.com js-eu1.hs-scripts.com pips.taboola.com cds.taboola.com am-trc-events.taboola.com 15.taboola.com www.facebook.com trc.taboola.com trc-events.taboola.com reporting.services.disqus.com tempest.services.disqus.com snap.licdn.com disqus.com c.disquscdn.com maps.gstatic.com feedburner.google.com s3.feedly.com menefex.disqus.com images.ctfassets.net maps.googleapis.com www.gstatic.com unpkg.com fonts.gstatic.com i.postimg.cc connect.facebook.net d33wubrfki0l68.cloudfront.net cdnjs.cloudflare.com fonts.googleapis.com analytics.google.com links.services.disqus.com pagead2.googlesyndication.com stats.g.doubleclick.net www.google-analytics.com www.google.nl; font-src 'self' data: chrome-extension fonts.gstatic.com; frame-src 'self' tempest.services.disqus.com disqus.com googleads.g.doubleclick.net open.spotify.com pagead2.googlesyndication.com tpc.googlesyndication.com web.facebook.com www.facebook.com www.google.com; img-src 'self' data: track-eu1.hubspot.com forms-eu1.hsforms.com region1.google-analytics.com www.soolide.com sb.scorecardresearch.com images.taboola.com i.ytimg.com content-cdn.tipsenweetjes.nl am-trc-events.taboola.com trc-events.taboola.com ce.lijit.com cdn.taboola.com px4.ads.linkedin.com www.linkedin.com px.ads.linkedin.com www.google.es stats.g.doubleclick.net www.googletagmanager.com d33wubrfki0l68.cloudfront.net www.google.co.in www.gstatic.com cdn.viglink.com links.services.disqus.com c.disquscdn.com referrer.disqus.com feedburner.google.com i.postimg.cc images.ctfassets.net maps.googleapis.com maps.gstatic.com pagead2.googlesyndication.com s3.feedly.com www.facebook.com www.google-analytics.com www.google.com www.google.nl www.google.be; manifest-src 'self'; media-src 'self'; prefetch-src 'self' translate.googleapis.com disqus.com c.disquscdn.com pagead2.googlesyndication.com partner.googleadservices.com adservice.google.nl adservice.google.com www.googletagservices.com www.googletagmanager.com www.google-analytics.com connect.facebook.net cdnjs.cloudflare.com fonts.googleapis.com maps.googleapis.com unpkg.com; worker-src 'self'; form-action 'self'; frame-ancestors 'self'; upgrade-insecure-requests; report-uri https://menefex.report-uri.com/r/d/csp/wizard; report-to default;"

    Expect-CT = 'enforce, 0, report-uri="https://menefex.report-uri.com/r/d/ct/reportOnly"'

    Permissions-Policy = 'geolocation=(self "https://menefex.nl/*"), microphone=(), fullscreen=(self "https://menefex.nl/*"), camera=()'
    
  [Report-To]
    group = "default"
    max_age = 31_536_000
    include_subdomains = true

    [[Report-To.endpoints]]
      url = "https://menefex.report-uri.com/a/d/g"

  [NEL]
    report_to = "default"
    max_age = 31_536_000
    include_subdomains = true